### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by 607mark** [manttoni/minishell#1]
Project Checklist for Minishell (Mandatory Part)

1. a Makefile that:

- [x] Compiles the project with -Wall, -Wextra, and -Werror.

- [x] Contains the rules: $(NAME), all, clean, fclean, re.

- [x] Does not relink unnecessarily.

2. Shell Functionality

- [x] Display a prompt when waiting for a command.

- [x] Implement a working history.

- [x] Search and launch the correct executable:

- [x] Based on the PATH variable.

- [x] Using a relative or absolute path.

- [x] Use only one global variable to manage received signals.

3. Quote Handling

- [x] Handle single quotes (') to prevent shell from interpreting meta-characters.

- [x] Handle double quotes (") but allow $ (dollar sign) to be interpreted within.

4. Redirection Implementation

- [x] Implement input redirection (<).

- [x] Implement output redirection (>).

- [x] Implement here-document (<<):

- [x] Read until a delimiter is encountered.

- [x] No history update required.

- [x] Implement append mode output redirection (>>).

5. Pipe Implementation

- [x] Implement pipes

6. Environment Variables

- [x] Handle environment variables ($ followed by a sequence of characters).

- [x] Handle ? to expand the exit status of the last executed command.

7. Signal Handling

- [x] Handle the following signals in interactive mode:

- [x] Ctrl-C: display a new prompt on a new line.

- [x] Ctrl-D: exit the shell.

- [x] **Ctrl-**: does nothing.

8. Built-in Commands

- [x] Implement the following built-in commands:

- [x] echo with -n option.

- [x] cd with relative or absolute paths.

- [x] pwd without options.

- [x] export without options.

- [x] unset without options.

- [x] env without arguments or options.

- [x] exit without options.

9. Leaks

- [x] Prevent all the possible leaks

10. Submission
- [x] Ensure correct file naming and content.
- [x] Norminette
- [x] Comprehensive testing
