### ISSUE TITLE
Signals checklist

### ISSUE THREAD

**Issue by 607mark** [manttoni/minishell#25]
main signals
- [x] Ctrl-C: display a new prompt on a new line.
- [x] Ctrl-D: exit the shell.
- [x]  **Ctrl-*\*: does nothing.

here_doc signals
- [x] Ctrl-C: exit current prompt and display a new prompt on a new line.
- [x] Ctrl-D: show error message but execute prompt.
- [x]  **Ctrl-*\*: does nothing.

fork signals
- [ ] Ctrl-C: 
- [ ] Ctrl-D: 
- [x]  **Ctrl-*\*:
